### PR TITLE
Fix structured output multi-turn conversation error

### LINKED ISSUE #497: [BUG] Schema breaks multi-turn conversations after persistence
### Basic checks

- [x] I searched existing issues - this hasn't been reported
- [x] I can reproduce this consistently
- [x] This is a RubyLLM bug, not my application code

### What's broken?

Structured schema responses cause `BadRequestError: Invalid request` in multi-turn conversations when messages are persisted. OpenAI API receives a Hash object instead of a JSON string for the message content.

### How to reproduce

```ruby
class PersonSchema < RubyLLM::Schema
  string :name, description: "Person's full name"
  integer :age, description: "Person's age in years"
  string :city, description: "City where they live"
end

chat_record = Chat.create!(model: 'gpt-4.1-nano')
chat_record.with_schema(PersonSchema)
response = chat_record.ask("Generate a person from Paris")
chat_record.with_schema(nil)
chat_record.ask("Generate a fictional bio for this person")
```

### Expected behavior

Structured response from the first message should be serialized as a JSON string when included in the message history for subsequent API calls.

### What actually happened

Structured response is sent as a Hash:

```
request -- POST https://api.openai.com/v1/chat/completions
request -- {:model=>"gpt-4.1-nano",
 :messages=>
  [{:role=>"user", :content=>"Generate a person from Paris"},
   {:role=>"assistant",
    :content=>{"name"=>"Sophie Laurent", "age"=>29, "city"=>"Paris"}},
   {:role=>"user", :content=>"Generate a fictional bio for this person"}],
 :stream=>false}
RubyLLM: API call failed, destroying message: 2322
Invalid type for 'messages[1].content': expected one of a string or array of objects, but got an object instead. (RubyLLM::BadRequestError)
```

### Environment

- RubyLLM version: 1.9.1 (working in 1.8.2)
- Provider: OpenAI

### PR DESCRIPTION
**Pull request by alexey-hunter-io**
## What this does

Fixes multi-turn conversation error when using `with_schema` for structured output. The persisted Hash/Array response was being passed directly to OpenAI instead of being serialized as a JSON string.

OpenAI API expects message content to be a string, so structured output Hashes/Arrays stored in `content_raw` must be converted to JSON when replayed.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation
- [ ] Performance improvement

## Scope check

- [x] I read the [Contributing Guide](https://github.com/crmne/ruby_llm/blob/main/CONTRIBUTING.md)
- [x] This aligns with RubyLLM's focus on **LLM communication**
- [x] This isn't application-specific logic that belongs in user code
- [x] This benefits most users, not just my specific use case

## Quality check

- [x] I ran `overcommit --install` and all hooks pass
- [x] I tested my changes thoroughly
  - [ ] For provider changes: Re-recorded VCR cassettes with `bundle exec rake vcr:record[provider_name]`
  - [x] All tests pass: `bundle exec rspec`
- [ ] I updated documentation if needed
- [x] I didn't modify auto-generated files manually (`models.json`, `aliases.json`)

## API changes

- [ ] Breaking change
- [ ] New public methods/classes
- [ ] Changed method signatures
- [x] No API changes

## Related issues

Fixes #497

### CODE REVIEW

File: lib/ruby_llm/providers/openai/media.rb [hunk 1]
```diff
@@ -8,7 +8,9 @@ module Media
         module_function
 
         def format_content(content) # rubocop:disable Metrics/PerceivedComplexity
-          return content.value if content.is_a?(RubyLLM::Content::Raw)
+          if content.is_a?(RubyLLM::Content::Raw)
+            return content.value.is_a?(Hash) ? content.value.to_json : content.value
+          end
           return content.to_json if content.is_a?(Hash) || content.is_a?(Array)
           return content unless content.is_a?(Content)
```
Comment (nerlichman) [inline lib/ruby_llm/providers/openai/media.rb]: Looks like the same logic is done on `Content::Raw` for Hash/Array but using value instead of directly using content.

Maybe something like this could work too:

```ruby
value = content.is_a?(RubyLLM::Content::Raw) ? content.value : content

return value.to_json if value.is_a?(Hash) || value.is_a?(Array)

return content unless content.is_a?(Content)
```

Comment (alexey-hunter-io) [reply lib/ruby_llm/providers/openai/media.rb]: Thanks! I've added an array check for consistency

**Comment by alexey-hunter-io** [comment]
@crmne Is there anything I can do to help get this fix merged? Thanks!
