### PR TITLE
Fix compatibility issue with URL attachments wrong number of arguments

### LINKED ISSUE #247: [BUG] wrong number of arguments when passing files for ask method
### Basic checks

- [x] I searched existing issues - this hasn't been reported
- [x] I can reproduce this consistently
- [x] This is a RubyLLM bug, not my application code

### What's broken?

ruby: ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [x86_64-linux]
ruby_llm: 1.3.0

To reproduce:

```
document = Document.first
# url of an existing file
file_path = document.file_url
client = RubyLLM.chat(model: "claude-3-7-sonnet")
client.ask "hello", with: { pdf: file_path }
```

Returns:

`'<main>': wrong number of arguments (given 2, expected 0..1) (ArgumentError)`

When testing on 1.2.0, it works just fine with the same code.

On my machine, it does work with 1.3.0, so I saw that issue in my production env only.
Ruby version on my machine: `ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [arm64-darwin24]`

### How to reproduce

```
file_path = <url-of-an-accessible-file-path>
client = RubyLLM.chat(model: "claude-3-7-sonnet")
client.ask "hello", with: { pdf: file_path } #error
client.ask "hello", with: file_path #error
```

### Expected behavior

Same as in 1.2.0, a request is sent to claude and an answer is returned from the LLM.

### What actually happened

`wrong number of arguments (given 2, expected 0..1) (ArgumentError)`

### Environment

ruby: `ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [x86_64-linux]`
ruby_llm: `1.3.0`

### PR DESCRIPTION
**Pull request by DustinFisher**
- Fix ArgumentError: wrong number of arguments (given 2, expected 0..1) that occurs when Marcel processes URI objects
- Use filename-based MIME detection for URLs instead of passing URI objects to Marcel
- Add test that reproduces the issue and validates the fix
- Maintains backward compatibility and improves performance by avoiding network calls

Screenshot 2025-06-16 at 9 34 13 AM

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation
- [ ] Performance improvement

## Scope check

- [x] I read the [Contributing Guide](https://github.com/crmne/ruby_llm/blob/main/CONTRIBUTING.md)
- [x] This aligns with RubyLLM's focus on **LLM communication**
- [x] This isn't application-specific logic that belongs in user code
- [x] This benefits most users, not just my specific use case

## Quality check

- [x] I ran `overcommit --install` and all hooks pass
- [x] I tested my changes thoroughly
- [ ] I updated documentation if needed
- [x] I didn't modify auto-generated files manually (`models.json`, `aliases.json`)

## API changes

- [ ] Breaking change
- [ ] New public methods/classes
- [ ] Changed method signatures
- [x] No API changes

## Related issues

Fixes #247

### CODE REVIEW

File: lib/ruby_llm/attachment.rb [hunk 1]
```diff
@@ -99,7 +99,7 @@ def to_h
     def determine_mime_type
       return @mime_type = active_storage_content_type if active_storage? && active_storage_content_type.present?
 
-      @mime_type = RubyLLM::MimeType.for(@source, name: @filename)
+      @mime_type = url? ? RubyLLM::MimeType.for(nil, name: @filename) : RubyLLM::MimeType.for(@source, name: @filename)
```
Comment (crmne) [inline lib/ruby_llm/attachment.rb]: `@mime_type = RubyLLM::MimeType.for(url? ? nil : @source, name: @filename)`

**Review by crmne — CHANGES_REQUESTED** [review]
Thank you for this!

I suggested a readability improvement.

**Review by crmne — APPROVED** [review]
