### PR TITLE
fix(#403): Don't specify default values on mysql json

### LINKED ISSUE #403: [BUG] CreateModels migration fails on MySQL
### Basic checks

- [x] I searched existing issues - this hasn't been reported
- [x] I can reproduce this consistently
- [x] This is a RubyLLM bug, not my application code

### What's broken?

MySQL can't have defaults for `json` columns. 

This is technically not true, but there's no way I've seen to get Rails to run the proper commands.

### How to reproduce

1. Configure RubyLLM in an app with a MySQL database
2. `rails generate ruby_llm:upgrade_to_v1_7`
3. `rails db:migrate`

### Expected behavior

Migrations run successfully.

### What actually happened

```
== 20250911174018 CreateModels: migrating =====================================
-- create_table(:models)
rake aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'modalities' can't have a default value
/Users/mmoen/code/github.com/vivoaquatics/part-deux/db/migrate/20250911174018_create_models.rb:3:in 'CreateModels#change'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'modalities' can't have a default value (ActiveRecord::StatementInvalid)
/Users/mmoen/code/github.com/vivoaquatics/part-deux/db/migrate/20250911174018_create_models.rb:3:in 'CreateModels#change'
```

### Environment

- Ruby Version: 3.4.5
- RubyLLM Version: 1.7.1
- Database Version: MySQL 8.0.43
- OS: any

### PR DESCRIPTION
**Pull request by UnderpantsGnome**
## What this does

Add logic branches for MySQL to skip the defaults.

## Type of change

- [x] Bug fix

## Scope check

- [x] I read the [Contributing Guide](https://github.com/crmne/ruby_llm/blob/main/CONTRIBUTING.md)
- [ ] This aligns with RubyLLM's focus on **LLM communication**
- [x] This isn't application-specific logic that belongs in user code
- [x] This benefits most users, not just my specific use case

## Quality check

- [x] I ran `overcommit --install` and all hooks pass
- [x] I tested my changes thoroughly
  - [ ] For provider changes: Re-recorded VCR cassettes with `bundle exec rake vcr:record[provider_name]`
  - [x] All tests pass: `bundle exec rspec`
- [ ] I updated documentation if needed
- [ ] I didn't modify auto-generated files manually (`models.json`, `aliases.json`)

## API changes

- [ ] Breaking change
- [ ] New public methods/classes
- [ ] Changed method signatures
- [x] No API changes

## Related issues

Fixes #403

### CODE REVIEW

File: lib/generators/ruby_llm/generator_helpers.rb [hunk 1]
```diff
@@ -120,6 +120,12 @@ def postgresql?
         false
       end
 
+      def mysql?
+        ::ActiveRecord::Base.connection.adapter_name.downcase.include?('mysql')
```
Comment (VincentZhao) [inline lib/generators/ruby_llm/generator_helpers.rb:124]: also should consider "trilogy"
